### ISSUE TITLE
letsencrypt certificates folder

### ISSUE THREAD

**Issue by ghiamar** [enoch85/ownCloud-VM#11]
Hi, your letsencrypt script looks up for certs in /opt/letsencrypt/live, but the latest letsencrypt saves them on /etc/letsencrypt/live.

Maybe you should also revied the finally cleaning part, because you may want to renew the certs because they live for three monts only...

**Comment by enoch85** [comment]
@ghiamar Thanks for your contributions! 

Do you think you could create a PR with you suggested changes? Thanks!

**Comment by enoch85** [comment]
Tasks:
1. Make necessary changes
2. Test the script so that it successfully creates a valid cert
3. If not, make more changes until it does.

Thank you in advance!

**Comment by ghiamar** [comment]
sorry @enoch85 i'm not quite well at shell scripting, will try and let you know

**Comment by enoch85** [comment]
@ghiamar It's OK. I made some smaller changes according to your comments here: https://github.com/enoch85/ownCloud-VM/commit/c29f1494d3938bbe8eb1f1d6ab639c99fa18b21b

Regarding the cleanup, it only happens if the script fails, otherwise the config remains.

Would be super if you could update the script to a working version. It was a long time ago I worked on this.

**Comment by ghiamar** [comment]
> Regarding the cleanup, it only happens if the script fails, otherwise the config remains.
Silly me, now I remember that I reached that conslusion yesterday...will have to sleep a little longer! jajaja.

Anyway, I can confirm that this line worked for me
`./letsencrypt-auto certonly --standalone -d www.mydomain.com`

Remember that I ran everthing by hand, didn't actually ran your scripts, but looked very well for me.

**Comment by enoch85** [comment]
Ok, nice to hear. That one is included in the first try. So cased closed then. Thanks for testing!
