### ISSUE TITLE
productoin install script 

### ISSUE THREAD

**Issue by ghiamar** [enoch85/ownCloud-VM#12]
Hi, in owncloud_install_production.sh you never ask for ocadmin linux user creation, maybe you need to create it in the script or ask the user to create it first. It happened to me in my clean VM install.

**Comment by enoch85** [comment]
@ghiamar These scripts are not intended to run from a clean VM. I use "BASE_VMs" and built from them. 

Note to self: add if argument and check if ocadmin exists, otherwise create ocadmin.

**Comment by ghiamar** [comment]
Great, hanks!
